GET http://localhost:3004/api/blogs

###
GET http://localhost:3004/api/blogs/641acfead8b1c7d8653d4f38

###
POST http://localhost:3004/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Blog with token user",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html"
}

###
DELETE http://localhost:3004/api/blogs/641dafce4cf3fdfe08411854 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImlkIjoiNjQxZDc5NzU4M2NjM2Q0Nzc2ODhhYTA4IiwiaWF0IjoxNjc5NzUyNDQwLCJleHAiOjE2Nzk3NTYwNDB9._GfL30WFdisb-B22fhppSIVhzYuSr3OMH65r1kz_-wo

###
PUT http://localhost:3004/api/blogs/641aeb0220c48e59efda951 HTTP/1.1
Content-Type: application/json

{
    "title": "Type Wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "likes": 10
}
